Iter9
shekshuev/shortener pull request #10
Opened 2024-10-21 20:01 UTC by shekshuev

2024-10-22 14:10 UTC, arttet requested changes

2024-10-22 14:10 UTC, arttet commented on cmd/shortener/main.go
> +	"go.uber.org/zap"
[CHANGE REQUEST] Please sort imports

2024-10-22 14:10 UTC, arttet commented on internal/app/compress/gzip.go
> +	if statusCode < 300 {
[CHANGE REQUEST] This is a magic number

2024-10-22 14:10 UTC, arttet commented on internal/app/store/url_store.go
> +func (s *URLStore) persist(key string) error {
[CHANGE REQUEST] Please follow the Single-responsibility principle

2024-10-22 14:10 UTC, arttet commented on internal/app/store/url_store.go
> +	if _, err := os.Stat(cfg.FileStoragePath); err == nil {
[CHANGE REQUEST] Please follow the Single-responsibility principle

2024-10-22 14:10 UTC, arttet commented on internal/app/middleware/gzip.go
> +		ow := w
[CHANGE REQUEST] This name is too short.

2024-10-22 14:10 UTC, arttet commented on internal/app/logger/logger.go
> +var Log *zap.Logger = zap.NewNop()
[CHANGE REQUEST] Please don't use global variables

2024-10-22 14:10 UTC, arttet commented on internal/app/handler/url_handler.go
> +func conveyor(h http.HandlerFunc, middlewares ...Middleware) http.HandlerFunc {
[CHANGE REQUEST] Let's simplify it.

2024-10-22 14:10 UTC, arttet commented on internal/app/handler/url_handler.go
> +	if r.Method == http.MethodPost {
[CHANGE REQUEST] Please follow the Go style

2024-10-22 14:10 UTC, arttet commented on internal/app/store/url_store.go
> +type serializeData struct {
[CHANGE REQUEST] It should be in the `dto` package.

2024-10-25 13:32 UTC, arttet requested changes

2024-10-25 13:32 UTC, arttet commented on internal/app/logger/logger.go
> +	instance *Logger
[CHANGE REQUEST] Please don't use global variables

2024-10-25 13:32 UTC, arttet commented on internal/app/store/url_store_snapshot.go
> +	for key, value := range store.urls {
[CHANGE REQUEST] Please follow the Open–closed principle

2024-10-25 13:32 UTC, arttet commented on internal/app/store/url_store.go
> +	return CreateSnapshot(s)
[CHANGE REQUEST] We should do it only once at the end of the program's execution.

2024-10-28 09:52 UTC, arttet requested changes

2024-10-28 09:52 UTC, arttet commented on internal/app/handler/url_handler.go
> +	if longURL, err := h.service.GetLongURL(r.URL.Path[1:]); err == nil {
`r.URL.Path[1:]` it looks like unsafe.

2024-10-28 09:52 UTC, arttet commented on internal/app/logger/logger.go
> +	instance *Logger
This comment remains relevant.

2024-10-28 09:52 UTC, arttet commented on internal/app/store/url_store_snapshot.go
> +	file, err := os.OpenFile(s.cfg.FileStoragePath, os.O_CREATE|os.O_WRONLY, 0644)
[SUGGESTION] This solution will be difficult to maintain and extend, violates SOLID principles, and distorts the essence of the task.

2024-10-29 21:14 UTC, shekshuev commented on internal/app/logger/logger.go
> +	instance *Logger
паттерн синглтон, поэтому глобальная переменная

2024-10-29 21:16 UTC, shekshuev commented on internal/app/store/url_store_snapshot.go
> +	file, err := os.OpenFile(s.cfg.FileStoragePath, os.O_CREATE|os.O_WRONLY, 0644)
утверждение субъективно и не обосновано. Хотелось бы более подробного ответа, почему так

2024-11-02 09:21 UTC, Bazys reviewed
у меня будет только один комментарий - папка app лишняя в го.

2024-11-02 09:24 UTC, merged